<?php

/**
 * ApiBarcodeController - controller
 *
 * Controller to handle barcodes-api-endpoint.
 * Returns all available barcodes generated by BarcodeService.
 *
 */

namespace App\Http\Controllers;

use App\Services\BarcodeService;
use Barryvdh\DomPDF\Facade\Pdf;

class ApiBarcodeController extends Controller
{

    public function __construct(private BarcodeService $barcodeService) {}

    public function index()
    {
        $barcodes = $this->barcodeService->generateAll();
        return response()->json($barcodes);
    }

}
